name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: ${{ secrets.CX_PROJECTNAME }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          base_uri: ${{ secrets.CX_BASEURI }}
          cx_client_id: ${{ secrets.CXCLIENT_ID }}
          cx_client_secret: ${{ secrets.CXCLIENT_SECRETS }}
          break_build: false
          scanners: sast
          bug_tracker: Sarif
          params: --namespace=${{ github.repository_owner }} --checkmarx.settings-override=true --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --cx-flow.filterSeverity --cx-flow.filterCategory --report-format sarif --output-path . cx_result.sarif  --checkmarx.disable-clubbing=true
          additional_params: --report-format sarif --output-path .
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with: 
           sarif_file: cx_result.sarif
          
